# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # tags: 
    #   - "v*"
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: '12'
  #     - run: npm install
  #     - run: npm run build
  #     - name: Save built zip file
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: release
  #         path: release.zip

  # create-release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Get built zip file
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: release
  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         files: |
  #           *.zip
  deploy:
    runs-on: ubuntu-latest
    # needs: [create-release]
    steps:
      - name: Sync with wp-cli
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: source ./.bashrc && wp plugin list
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
